<?php declare(strict_types = 1);

/**
 * This file is part of the FireHub Project ecosystem
 *
 * Pre-generated mapping of fully qualified class names to their file paths.
 * @since 1.0.0
 *
 * @author Danijel Galić <danijel.galic@outlook.com>
 * @copyright 2026 The FireHub Project - All rights reserved
 * @license https://opensource.org/licenses/MIT MIT License
 *
 * @php-version 7.0
 * @package Core\Support
 */

namespace FireHub\Core\Support\Autoload;

/**
 * ### Pre-generated mapping of fully qualified class names to their file paths
 *
 * This file is used by the FireHub autoloader to resolve classes without performing filesystem scanning,
 * significantly reducing bootstrap time.<br>
 * The classmap is generated during the build process and should not be modified manually.
 * @since 1.0.0
 *
 * @return array<class-string, non-empty-string>
 */
return [
    \FireHub\Core\Domain\Autoload\Handle::class => __DIR__.'/../../domain/autoload/firehub.Handle.php',
    \FireHub\Core\FireHub::class => __DIR__.'/../../firehub.FireHub.php',
    \FireHub\Core\Shared\Contracts\ArrayConvertable::class => __DIR__.'/../../shared/contracts/firehub.ArrayConvertable.php',
    \FireHub\Core\Shared\Contracts\Arrayable::class => __DIR__.'/../../shared/contracts/firehub.Arrayable.php',
    \FireHub\Core\Shared\Contracts\Countable::class => __DIR__.'/../../shared/contracts/firehub.Countable.php',
    \FireHub\Core\Shared\Contracts\Iterator::class => __DIR__.'/../../shared/contracts/firehub.Iterator.php',
    \FireHub\Core\Shared\Contracts\IteratorAggregate::class => __DIR__.'/../../shared/contracts/firehub.IteratorAggregate.php',
    \FireHub\Core\Shared\Contracts\JsonSerializable::class => __DIR__.'/../../shared/contracts/firehub.JsonSerializable.php',
    \FireHub\Core\Shared\Contracts\JsonSerializableConvertable::class => __DIR__.'/../../shared/contracts/firehub.JsonSerializableConvertable.php',
    \FireHub\Core\Shared\Contracts\Magic\Serializable::class => __DIR__.'/../../shared/contracts/magic/firehub.Serializable.php',
    \FireHub\Core\Shared\Contracts\Magic\SerializableConvertable::class => __DIR__.'/../../shared/contracts/magic/firehub.SerializableConvertable.php',
    \FireHub\Core\Shared\Contracts\Magic\Stringable::class => __DIR__.'/../../shared/contracts/magic/firehub.Stringable.php',
    \FireHub\Core\Shared\Contracts\Throwable::class => __DIR__.'/../../shared/contracts/firehub.Throwable.php',
    \FireHub\Core\Shared\Contracts\Traversable::class => __DIR__.'/../../shared/contracts/firehub.Traversable.php',
    \FireHub\Core\Shared\Enums\Comparison::class => __DIR__.'/../../shared/enums/firehub.Comparison.php',
    \FireHub\Core\Shared\Enums\ControlFlow\Signal::class => __DIR__.'/../../shared/enums/controlflow/firehub.Signal.php',
    \FireHub\Core\Shared\Enums\Data\Category::class => __DIR__.'/../../shared/enums/data/firehub.Category.php',
    \FireHub\Core\Shared\Enums\Data\ResourceType::class => __DIR__.'/../../shared/enums/data/firehub.ResourceType.php',
    \FireHub\Core\Shared\Enums\Data\Type::class => __DIR__.'/../../shared/enums/data/firehub.Type.php',
    \FireHub\Core\Shared\Enums\DateTime\Format\Predefined::class => __DIR__.'/../../shared/enums/datetime/format/firehub.Predefined.php',
    \FireHub\Core\Shared\Enums\DateTime\Zone::class => __DIR__.'/../../shared/enums/datetime/firehub.Zone.php',
    \FireHub\Core\Shared\Enums\FileSystem\Permission::class => __DIR__.'/../../shared/enums/filesystem/firehub.Permission.php',
    \FireHub\Core\Shared\Enums\Json\Flag::class => __DIR__.'/../../shared/enums/json/firehub.Flag.php',
    \FireHub\Core\Shared\Enums\Json\Flag\Decode::class => __DIR__.'/../../shared/enums/json/flag/firehub.Decode.php',
    \FireHub\Core\Shared\Enums\Json\Flag\Encode::class => __DIR__.'/../../shared/enums/json/flag/firehub.Encode.php',
    \FireHub\Core\Shared\Enums\Json\Flag\Error::class => __DIR__.'/../../shared/enums/json/flag/firehub.Error.php',
    \FireHub\Core\Shared\Enums\Json\Flag\Validate::class => __DIR__.'/../../shared/enums/json/flag/firehub.Validate.php',
    \FireHub\Core\Shared\Enums\Number\LogBase::class => __DIR__.'/../../shared/enums/number/firehub.LogBase.php',
    \FireHub\Core\Shared\Enums\Number\Round::class => __DIR__.'/../../shared/enums/number/firehub.Round.php',
    \FireHub\Core\Shared\Enums\Order::class => __DIR__.'/../../shared/enums/firehub.Order.php',
    \FireHub\Core\Shared\Enums\Side::class => __DIR__.'/../../shared/enums/firehub.Side.php',
    \FireHub\Core\Shared\Enums\String\CaseFolding::class => __DIR__.'/../../shared/enums/string/firehub.CaseFolding.php',
    \FireHub\Core\Shared\Enums\String\Compare::class => __DIR__.'/../../shared/enums/string/firehub.Compare.php',
    \FireHub\Core\Shared\Enums\String\Count\CharacterMode::class => __DIR__.'/../../shared/enums/string/count/firehub.CharacterMode.php',
    \FireHub\Core\Shared\Enums\String\Count\WordFormat::class => __DIR__.'/../../shared/enums/string/count/firehub.WordFormat.php',
    \FireHub\Core\Shared\Enums\String\Encoding::class => __DIR__.'/../../shared/enums/string/firehub.Encoding.php',
    \FireHub\Core\Shared\Enums\String\Sort::class => __DIR__.'/../../shared/enums/string/firehub.Sort.php',
    \FireHub\Core\Shared\Enums\SystemRuntime\IniAccessLevel::class => __DIR__.'/../../shared/enums/systemruntime/firehub.IniAccessLevel.php',
    \FireHub\Core\Shared\Enums\SystemRuntime\PhpExtension::class => __DIR__.'/../../shared/enums/systemruntime/firehub.PhpExtension.php',
    \FireHub\Core\Shared\ValueObject::class => __DIR__.'/../../shared/firehub.ValueObject.php',
    \FireHub\Core\Support\Autoload::class => __DIR__.'/../../support/firehub.Autoload.php',
    \FireHub\Core\Support\Autoload\Loader::class => __DIR__.'/../../support/autoload/firehub.Loader.php',
    \FireHub\Core\Support\Autoload\Loader\Classmap::class => __DIR__.'/../../support/autoload/loader/firehub.Classmap.php',
    \FireHub\Core\Support\Autoload\Loader\CompiledClassmap::class => __DIR__.'/../../support/autoload/loader/firehub.CompiledClassmap.php',
    \FireHub\Core\Support\Autoload\Loader\Resolver::class => __DIR__.'/../../support/autoload/loader/firehub.Resolver.php',
    \FireHub\Core\Support\Bootstrap\Bootloader::class => __DIR__.'/../../support/bootstrap/firehub.Bootloader.php',
    \FireHub\Core\Support\Bootstrap\Bootloader\RegisterAutoloaders::class => __DIR__.'/../../support/bootstrap/bootloader/firehub.RegisterAutoloaders.php',
    \FireHub\Core\Support\Bootstrap\Bootloader\RegisterConstants::class => __DIR__.'/../../support/bootstrap/bootloader/firehub.RegisterConstants.php',
    \FireHub\Core\Support\Bootstrap\Bootloader\RegisterHelpers::class => __DIR__.'/../../support/bootstrap/bootloader/firehub.RegisterHelpers.php',
    \FireHub\Core\Support\Bootstrap\FireHubConfigurator::class => __DIR__.'/../../support/bootstrap/firehub.FireHubConfigurator.php',
    \FireHub\Core\Support\Contracts\DataStructure::class => __DIR__.'/../../support/contracts/firehub.DataStructure.php',
    \FireHub\Core\Support\DataStructure\Abstraction\Collection::class => __DIR__.'/../../support/datastructure/abstraction/firehub.Collection.php',
    \FireHub\Core\Support\DataStructure\Abstraction\Enumerable::class => __DIR__.'/../../support/datastructure/abstraction/firehub.Enumerable.php',
    \FireHub\Core\Support\DataStructure\Abstraction\Stream::class => __DIR__.'/../../support/datastructure/abstraction/firehub.Stream.php',
    \FireHub\Core\Support\DataStructure\Builder\SequenceBuilder::class => __DIR__.'/../../support/datastructure/builder/firehub.SequenceBuilder.php',
    \FireHub\Core\Support\DataStructure\Capability\Access\RandomAccess::class => __DIR__.'/../../support/datastructure/capability/access/firehub.RandomAccess.php',
    \FireHub\Core\Support\DataStructure\Capability\Access\SequentialAccess::class => __DIR__.'/../../support/datastructure/capability/access/firehub.SequentialAccess.php',
    \FireHub\Core\Support\DataStructure\Capability\Access\StreamingAccess::class => __DIR__.'/../../support/datastructure/capability/access/firehub.StreamingAccess.php',
    \FireHub\Core\Support\DataStructure\Capability\Behavior\Countable::class => __DIR__.'/../../support/datastructure/capability/behavior/firehub.Countable.php',
    \FireHub\Core\Support\DataStructure\Collection\Linear\Sequence::class => __DIR__.'/../../support/datastructure/collection/linear/firehub.Sequence.php',
    \FireHub\Core\Support\DataStructure\DS::class => __DIR__.'/../../support/datastructure/firehub.DS.php',
    \FireHub\Core\Support\DataStructure\Storage::class => __DIR__.'/../../support/datastructure/firehub.Storage.php',
    \FireHub\Core\Support\DataStructure\Storage\ArrStorage::class => __DIR__.'/../../support/datastructure/storage/firehub.ArrStorage.php',
    \FireHub\Core\Support\DataStructure\Storage\GeneratorStorage::class => __DIR__.'/../../support/datastructure/storage/firehub.GeneratorStorage.php',
    \FireHub\Core\Support\DataStructure\Trait\EnumerableBehavior::class => __DIR__.'/../../support/datastructure/trait/firehub.EnumerableBehavior.php',
    \FireHub\Core\Support\DataStructure\Type\Linear::class => __DIR__.'/../../support/datastructure/type/firehub.Linear.php',
    \FireHub\Core\Support\LowLevel::class => __DIR__.'/../../support/firehub.LowLevel.php',
    \FireHub\Core\Support\LowLevel\Arr::class => __DIR__.'/../../support/lowlevel/firehub.Arr.php',
    \FireHub\Core\Support\LowLevel\CharMB::class => __DIR__.'/../../support/lowlevel/firehub.CharMB.php',
    \FireHub\Core\Support\LowLevel\CharSB::class => __DIR__.'/../../support/lowlevel/firehub.CharSB.php',
    \FireHub\Core\Support\LowLevel\ClsObj::class => __DIR__.'/../../support/lowlevel/firehub.ClsObj.php',
    \FireHub\Core\Support\LowLevel\Constant::class => __DIR__.'/../../support/lowlevel/firehub.Constant.php',
    \FireHub\Core\Support\LowLevel\Data::class => __DIR__.'/../../support/lowlevel/firehub.Data.php',
    \FireHub\Core\Support\LowLevel\DataIs::class => __DIR__.'/../../support/lowlevel/firehub.DataIs.php',
    \FireHub\Core\Support\LowLevel\DateAndTime::class => __DIR__.'/../../support/lowlevel/firehub.DateAndTime.php',
    \FireHub\Core\Support\LowLevel\Declared::class => __DIR__.'/../../support/lowlevel/firehub.Declared.php',
    \FireHub\Core\Support\LowLevel\FileSystem::class => __DIR__.'/../../support/lowlevel/firehub.FileSystem.php',
    \FireHub\Core\Support\LowLevel\Func::class => __DIR__.'/../../support/lowlevel/firehub.Func.php',
    \FireHub\Core\Support\LowLevel\Iterator::class => __DIR__.'/../../support/lowlevel/firehub.Iterator.php',
    \FireHub\Core\Support\LowLevel\Json::class => __DIR__.'/../../support/lowlevel/firehub.Json.php',
    \FireHub\Core\Support\LowLevel\Math::class => __DIR__.'/../../support/lowlevel/firehub.Math.php',
    \FireHub\Core\Support\LowLevel\Random::class => __DIR__.'/../../support/lowlevel/firehub.Random.php',
    \FireHub\Core\Support\LowLevel\Regex::class => __DIR__.'/../../support/lowlevel/firehub.Regex.php',
    \FireHub\Core\Support\LowLevel\RegexMB::class => __DIR__.'/../../support/lowlevel/firehub.RegexMB.php',
    \FireHub\Core\Support\LowLevel\Resources::class => __DIR__.'/../../support/lowlevel/firehub.Resources.php',
    \FireHub\Core\Support\LowLevel\SplAutoload::class => __DIR__.'/../../support/lowlevel/firehub.SplAutoload.php',
    \FireHub\Core\Support\LowLevel\StrMB::class => __DIR__.'/../../support/lowlevel/firehub.StrMB.php',
    \FireHub\Core\Support\LowLevel\StrSB::class => __DIR__.'/../../support/lowlevel/firehub.StrSB.php',
    \FireHub\Core\Support\LowLevel\SystemRuntime::class => __DIR__.'/../../support/lowlevel/firehub.SystemRuntime.php',
    \FireHub\Core\Testing\Base::class => __DIR__.'/../../testing/firehub.Base.php',
    \FireHub\Core\Throwable\Builder::class => __DIR__.'/../../throwable/firehub.Builder.php',
    \FireHub\Core\Throwable\Error::class => __DIR__.'/../../throwable/firehub.Error.php',
    \FireHub\Core\Throwable\ErrorBuilder::class => __DIR__.'/../../throwable/firehub.ErrorBuilder.php',
    \FireHub\Core\Throwable\Error\LowLevel\Arr\ChunkLengthTooSmallError::class => __DIR__.'/../../throwable/error/lowlevel/arr/firehub.ChunkLengthTooSmallError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Arr\FailedToSortMultiArrayError::class => __DIR__.'/../../throwable/error/lowlevel/arr/firehub.FailedToSortMultiArrayError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Arr\KeysAndValuesDiffNumberOfElemsError::class => __DIR__.'/../../throwable/error/lowlevel/arr/firehub.KeysAndValuesDiffNumberOfElemsError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Arr\OutOfRangeError::class => __DIR__.'/../../throwable/error/lowlevel/arr/firehub.OutOfRangeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Arr\RegisterAutoloadError::class => __DIR__.'/../../throwable/error/lowlevel/autoload/firehub.RegisterAutoloadError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Arr\SizeInconsistentError::class => __DIR__.'/../../throwable/error/lowlevel/arr/firehub.SizeInconsistentError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Arr\UnregisterAutoloaderError::class => __DIR__.'/../../throwable/error/lowlevel/autoload/firehub.UnregisterAutoloaderError.php',
    \FireHub\Core\Throwable\Error\LowLevel\ClsObj\ClassDoesntExistError::class => __DIR__.'/../../throwable/error/lowlevel/clsobj/firehub.ClassDoesntExistError.php',
    \FireHub\Core\Throwable\Error\LowLevel\ClsObj\FailedToCreateAliasError::class => __DIR__.'/../../throwable/error/lowlevel/clsobj/firehub.FailedToCreateAliasError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Constant\AlreadyExistError::class => __DIR__.'/../../throwable/error/lowlevel/constant/firehub.AlreadyExistError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Constant\FailedToDefineError::class => __DIR__.'/../../throwable/error/lowlevel/constant/firehub.FailedToDefineError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Constant\NotDefinedError::class => __DIR__.'/../../throwable/error/lowlevel/constant/firehub.NotDefinedError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Data\ArrayToStringConversionError::class => __DIR__.'/../../throwable/error/lowlevel/data/firehub.ArrayToStringConversionError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Data\CannotSerializeError::class => __DIR__.'/../../throwable/error/lowlevel/data/firehub.CannotSerializeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Data\FailedToSetTypeError::class => __DIR__.'/../../throwable/error/lowlevel/data/firehub.FailedToSetTypeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Data\SetAsResourceError::class => __DIR__.'/../../throwable/error/lowlevel/data/firehub.SetAsResourceError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Data\TypeUnknownError::class => __DIR__.'/../../throwable/error/lowlevel/data/firehub.TypeUnknownError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Data\UnserializeFailedError::class => __DIR__.'/../../throwable/error/lowlevel/data/firehub.UnserializeFailedError.php',
    \FireHub\Core\Throwable\Error\LowLevel\DateTime\FailedToFormatTimestampAsIntError::class => __DIR__.'/../../throwable/error/lowlevel/datetime/firehub.FailedToFormatTimestampAsIntError.php',
    \FireHub\Core\Throwable\Error\LowLevel\DateTime\FailedToGetZoneError::class => __DIR__.'/../../throwable/error/lowlevel/datetime/firehub.FailedToGetZoneError.php',
    \FireHub\Core\Throwable\Error\LowLevel\DateTime\FailedToSetZoneError::class => __DIR__.'/../../throwable/error/lowlevel/datetime/firehub.FailedToSetZoneError.php',
    \FireHub\Core\Throwable\Error\LowLevel\DateTime\FormatTimestampError::class => __DIR__.'/../../throwable/error/lowlevel/datetime/firehub.FormatTimestampError.php',
    \FireHub\Core\Throwable\Error\LowLevel\DateTime\ParseFromFormatError::class => __DIR__.'/../../throwable/error/lowlevel/datetime/firehub.ParseFromFormatError.php',
    \FireHub\Core\Throwable\Error\LowLevel\DateTime\StringToTimestampError::class => __DIR__.'/../../throwable/error/lowlevel/datetime/firehub.StringToTimestampError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\CannotListError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.CannotListError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\ChangeSymlinkGroupError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.ChangeSymlinkGroupError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\ChangeSymlinkOwnerError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.ChangeSymlinkOwnerError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\CopyPathError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.CopyPathError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\CreateFolderError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.CreateFolderError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\CreateLinkError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.CreateLinkError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\CreateSymlinkError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.CreateSymlinkError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\DeletePathError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.DeletePathError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\DiskSpaceError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.DiskSpaceError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetAbsolutePathError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetAbsolutePathError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetContentError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetContentError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetGroupError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetGroupError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetInodeError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetInodeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetLastAccessedError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetLastAccessedError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetLastChangedError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetLastChangedError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetLastModifiedError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetLastModifiedError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetOwnerError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetOwnerError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetPathSizeError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetPathSizeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetPermissionsError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetPermissionsError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetStatisticsError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetStatisticsError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\GetSymlinkError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.GetSymlinkError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\MoveUploadedFileError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.MoveUploadedFileError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\ParentLevelTooSmallError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.ParentLevelTooSmallError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\PathDoesntExistError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.PathDoesntExistError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\PutContentError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.PutContentError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\ReadFileError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.ReadFileError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\RenameError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.RenameError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\SearchError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.SearchError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\SetGroupError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.SetGroupError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\SetLastAccessAndModifyError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.SetLastAccessAndModifyError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\SetOwnerError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.SetOwnerError.php',
    \FireHub\Core\Throwable\Error\LowLevel\FileSystem\SetPermissionsError::class => __DIR__.'/../../throwable/error/lowlevel/filesystem/firehub.SetPermissionsError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Func\RegisterTickFailedError::class => __DIR__.'/../../throwable/error/lowlevel/func/firehub.RegisterTickFailedError.php',
    \FireHub\Core\Throwable\Error\LowLevel\InvalidValueObjectError::class => __DIR__.'/../../throwable/error/valueobject/firehub.InvalidValueObjectError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Json\DecodeError::class => __DIR__.'/../../throwable/error/lowlevel/json/firehub.DecodeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Json\EncodeError::class => __DIR__.'/../../throwable/error/lowlevel/json/firehub.EncodeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Number\ArithmeticError::class => __DIR__.'/../../throwable/error/lowlevel/number/firehub.ArithmeticError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Number\DivideByZeroError::class => __DIR__.'/../../throwable/error/lowlevel/number/firehub.DivideByZeroError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Random\MaxLessThanMinError::class => __DIR__.'/../../throwable/error/lowlevel/random/firehub.MaxLessThanMinError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Random\NumberGreaterThanMaxError::class => __DIR__.'/../../throwable/error/lowlevel/random/firehub.NumberGreaterThanMaxError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Random\NumberLessThanMinError::class => __DIR__.'/../../throwable/error/lowlevel/random/firehub.NumberLessThanMinError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Random\SecureNumberError::class => __DIR__.'/../../throwable/error/lowlevel/random/firehub.SecureNumberError.php',
    \FireHub\Core\Throwable\Error\LowLevel\Regex\InvalidPatternError::class => __DIR__.'/../../throwable/error/lowlevel/regex/firehub.InvalidPatternError.php',
    \FireHub\Core\Throwable\Error\LowLevel\String\ChunkLengthLessThanOneError::class => __DIR__.'/../../throwable/error/lowlevel/string/firehub.ChunkLengthLessThanOneError.php',
    \FireHub\Core\Throwable\Error\LowLevel\String\CodepointOutsideValidRangeError::class => __DIR__.'/../../throwable/error/lowlevel/string/firehub.CodepointOutsideValidRangeError.php',
    \FireHub\Core\Throwable\Error\LowLevel\String\ComparePartError::class => __DIR__.'/../../throwable/error/lowlevel/string/firehub.ComparePartError.php',
    \FireHub\Core\Throwable\Error\LowLevel\String\EmptyPadError::class => __DIR__.'/../../throwable/error/lowlevel/string/firehub.EmptyPadError.php',
    \FireHub\Core\Throwable\Error\LowLevel\String\EmptySeparatorError::class => __DIR__.'/../../throwable/error/lowlevel/string/firehub.EmptySeparatorError.php',
    \FireHub\Core\Throwable\Error\LowLevel\String\InvalidEncodingError::class => __DIR__.'/../../throwable/error/lowlevel/string/firehub.InvalidEncodingError.php',
    \FireHub\Core\Throwable\Error\LowLevel\SystemRuntime\FailedToGetProcessIDError::class => __DIR__.'/../../throwable/error/lowlevel/systemruntime/firehub.FailedToGetProcessIDError.php',
    \FireHub\Core\Throwable\Error\LowLevel\SystemRuntime\FailedToGetServerAPIError::class => __DIR__.'/../../throwable/error/lowlevel/systemruntime/firehub.FailedToGetServerAPIError.php',
    \FireHub\Core\Throwable\Error\LowLevel\SystemRuntime\FailedToSetConfigurationOptionError::class => __DIR__.'/../../throwable/error/lowlevel/systemruntime/firehub.FailedToSetConfigurationOptionError.php',
    \FireHub\Core\Throwable\Error\LowLevel\SystemRuntime\InvalidConfigurationOptionError::class => __DIR__.'/../../throwable/error/lowlevel/systemruntime/firehub.InvalidConfigurationOptionError.php',
    \FireHub\Core\Throwable\Error\LowLevel\SystemRuntime\InvalidConfigurationQuantityError::class => __DIR__.'/../../throwable/error/lowlevel/systemruntime/firehub.InvalidConfigurationQuantityError.php',
    \FireHub\Core\Throwable\Error\LowLevel\SystemRuntime\InvalidExtensionError::class => __DIR__.'/../../throwable/error/lowlevel/systemruntime/firehub.InvalidExtensionError.php',
    \FireHub\Core\Throwable\Error\LowLevel\SystemRuntime\SleepTimeInvalidError::class => __DIR__.'/../../throwable/error/lowlevel/systemruntime/firehub.SleepTimeInvalidError.php',
    \FireHub\Core\Throwable\Exception::class => __DIR__.'/../../throwable/firehub.Exception.php',
    \FireHub\Core\Throwable\ExceptionBuilder::class => __DIR__.'/../../throwable/firehub.ExceptionBuilder.php',
    \FireHub\Core\Throwable\Exception\DataStructure\WrongReturnTypeException::class => __DIR__.'/../../throwable/exception/datastructure/firehub.WrongReturnTypeException.php',
    \FireHub\Core\Throwable\Exception\Domain\Autoload\ImplementationException::class => __DIR__.'/../../throwable/exception/domain/autoload/firehub.ImplementationException.php',
    \FireHub\Core\Throwable\Exception\Domain\Autoload\InvalidFolderException::class => __DIR__.'/../../throwable/exception/domain/autoload/firehub.InvalidFolderException.php',
    \FireHub\Core\Throwable\Exception\Domain\Autoload\InvalidHandleException::class => __DIR__.'/../../throwable/exception/domain/autoload/firehub.InvalidHandleException.php',
    \FireHub\Core\Throwable\Exception\Domain\Autoload\InvalidNamespaceException::class => __DIR__.'/../../throwable/exception/domain/autoload/firehub.InvalidNamespaceException.php',
    \FireHub\Core\Throwable\Exception\Support\Bootstrap\FailedToLoadBootloaderException::class => __DIR__.'/../../throwable/exception/support/bootstrap/firehub.FailedToLoadBootloaderException.php',
    \FireHub\Core\Throwable\Exception\Support\Bootstrap\NotBootloaderException::class => __DIR__.'/../../throwable/exception/support/bootstrap/firehub.NotBootloaderException.php',
    \FireHub\Core\Throwable\Throwable::class => __DIR__.'/../../throwable/firehub.Throwable.php',
    \FireHub\Core\Throwable\ValueObject\Code::class => __DIR__.'/../../throwable/valueobject/firehub.Code.php',
];