name: PHPUnit with Codecov

on:
  push:
  pull_request:

permissions: read-all

jobs:
  build:
    uses: The-FireHub-Project/.github/.github/workflows/RunCommandOnMatrix.yml@master
    with:
      title: "Run PHPUnit"
      operatingSystems: '["ubuntu-latest", "windows-latest", "macOS-latest"]'
      phpVersions: ${{ vars.PHP_VERSIONS }}
      phpExtensions: ${{ vars.PHP_EXTENSIONS }}
      tools: "phpunit:13.x"
      command: |
        phpunit --testsuite unit --coverage-clover=coverage-unit.xml --log-junit junit-unit.xml
        phpunit --testsuite integration --coverage-clover=coverage-integration.xml --log-junit junit-integration.xml
        phpunit --testsuite smoke --coverage-clover=coverage-smoke.xml --log-junit junit-smoke.xml
      uploadArtifacts: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all OS artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: artifact-*
          path: ./artifacts
      - name: Upload Unit coverage
        uses: codecov/codecov-action@v5
        with:
          files: |
            ./artifacts/ubuntu-latest/coverage-unit.xml
          flags: unit
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}