name: Build & Release PHAR

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ inputs.phpExtensions }}
          tools: ${{ inputs.tools }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Load PRIVATE key
        run: echo "${{ secrets.FIREHUB_PRIVATE_KEY }}" > private.pem
      - name: Build PHAR
        run: php -d phar.readonly=0 phar/build.php
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: core
          path: |
            phar/core.phar
            phar/core.min.phar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            phar/core.phar
            phar/core.phar.pubkey
            phar/core.min.phar
            phar/core.min.phar.pubkey